name: flutter_libserialport_example
description: Demonstrates how to use the flutter_libserialport plugin.
publish_to: 'none'

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport:
    path: ../
  serial_port_win32: ^1.3.0
  win32: ^5.5.0

flutter:
  uses-material-design: true
